web:
  container_name: aminmkh/php7-apache-oci8 
  build: .
  ports:
    - "80:80"
  volumes:
    - ./:/var/www/html/
    - /conf/apache:/etc/apache2/sites-enabled/
    - /conf/php:/usr/local/etc/php/

